file:
  directory: D:/2024-02/download/tdd

spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3_test
    username: root
    password: green502
  sql:
    init:
      mode: always #resources아래에 있는 schema.sql(Table생성 DDL), data.sql(데이터 insert DML)파일을 프로젝트(테스트) 시작시 실행한다.